services:
  mysqla:
    image: mysql
    environment:
      MYSQL_DATABASE: nestjs_prisma
      MYSQL_ROOT_PASSWORD: password 
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"